# Generated by Django 5.0.4 on 2024-06-07 10:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('short_description', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_diseases)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDesicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_status', models.SmallIntegerField(default=0)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('file', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_userimages)),
                ('permission', models.BooleanField(blank=True, null=True)),
                ('classification', models.SmallIntegerField()),
                ('probability', models.FloatField()),
            ],
        ),
    ]
